---
# Custom role, see README.md role genisis
genisis_user: "{{ lookup('env','USER') }}"
# genisis_user_passwordless_sudoer: true # default: true
# genisis_group_sudo_passwordless_sudoers: true # default: true
# genisis_user_ssh_pubkey: ~/.ssh/id_ed25519.pub # default: ~/.ssh/id_ed25519.pub

# Custom role, see README.md role networking
# networking_ufw_rules: # default: []
#   - { rule: "allow", port: 19999, proto: "any", from_ip: "{{ wireguard_network }}" } # allow Netdata portal access from wireguard network
#   - { rule: "allow", port: 80, proto: "tcp" } # allow HTTP
#   - { rule: "allow", port: 443, proto: "tcp" } # allow HTTPS
#   - { rule: "allow", port: 443, proto: "udp" } # allow HTTP/2+

# For more options see https://github.com/geerlingguy/ansible-role-security
security_autoupdate_enabled: false # default: true
security_fail2ban_enabled: false # default: true

# For more options see https://github.com/geerlingguy/ansible-role-postgresql
# NOTE: postgresql_privs is a customization with my own role (see README.md role postgresql)
postgresql_users:
  - name: "{{ genisis_user }}"
    password: notasecurepassword
  - name: "netdata"
postgresql_privs:
  - database: postgres
    type: database
    privs: pg_monitor
    roles: netdata

# Custom role, see README.md role netdata
netdata_api_key: "00000000-0000-0000-0000-000000000000" # optional, required for parent config (generate with uuidgen)
netdata_go_d_postgres:
  - name: local
    dsn: 'host=/var/run/postgresql dbname=postgres user=netdata'
netdata_health_alarm_notify:
  - option: SEND_NTFY
    value: "YES"
  - option: DEFAULT_RECIPIENT_NTFY
    value: "https://ntfy.sh/REPLACEME"

# Wireguard settings
wireguard_network: 10.0.0.0/24 # default

# Custom WireGuard profiles
wireguard_export_custom_profiles: true # default: false
wireguard_custom_profiles: # default: []
  - name: desktop
    address: 10.0.0.100
    private_key: uM7nPA+rXKbxx3pOU5iunMNHj+S80L53R4BKzGCw+nY=
    public_key: RiHiil0d6btdH0t0leYKa0ddgFJUZQ3LQ/wAaS5VaAU=