---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: reboot_required_file

- name: Reboot the server (if required)
  reboot:
  when: reboot_required_file.stat.exists == true and upgrade_allow_reboot == true
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true
  become: yes