---
- name: Setup servers
  hosts: servers
  gather_facts: true
  remote_user: "{{ genisis_user }}"

  vars_files:
    - ../config.yml

  roles:
    - name: upgrade
      become: true
    - name: networking
      become: true
    - name: wireguard
      become: true
    - role: geerlingguy.postgresql
      become: true
    - role: netdata
      become: true
      
